const test=require('node:test'),assert=require('node:assert/strict'),D=require('../dist/data.js'),P=require('../dist/planning.js');
function state(){const w=P.emptyWeek(12);w.plan[0]='r';w.stockNotes='Öl prüfen';return{version:2,weekStart:'2026-09-14',recipes:[{id:'r',name:'Suppe',side:'Brot',allergens:'G',basePortions:10,ingredients:[{name:'Milch',amount:.5,unit:'l',category:'Kühlung'}]}],weeks:{'2026-09-14':w}};}
function storage(){const values=new Map([['main',JSON.stringify(state())]]);return{values,getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};}
test('backup round trip preserves all fields including shopping checks',()=>{const s=state();s.weeks[s.weekStart].checked=P.items(s.weeks[s.weekStart],s.recipes).map(x=>x.token);assert.deepEqual(D.parseBackup(D.backup(s)),s);});
test('rejects malformed, foreign, future and oversized backups',()=>{for(const value of ['{','null','{}',JSON.stringify({app:'kuechenplan',backupVersion:99,data:state()}),' '.repeat(10*1024*1024+1)])assert.throws(()=>D.parseBackup(value));});
test('rejects invalid ingredients, duplicate IDs, unknown references and impossible dates',()=>{const mutations=[s=>s.recipes[0].ingredients[0].amount=-1,s=>s.recipes[0].ingredients[0].unit='cup',s=>s.recipes[0].ingredients[0].category='unknown',s=>s.recipes.push(s.recipes[0]),s=>s.weeks[s.weekStart].plan[0]='missing',s=>s.weeks[s.weekStart].dayPortions[0]=1.5,s=>s.weekStart='2026-02-30',s=>s.weeks.__proto__={bad:true}];for(const mutate of mutations.slice(0,-1)){const s=state();mutate(s);assert.throws(()=>D.validateState(s));}});
test('duplicate can be edited without modifying the original ingredients',()=>{const original=state().recipes[0],copy=D.duplicate(original,'copy');copy.ingredients[0].amount=8;assert.equal(original.ingredients[0].amount,.5);assert.equal(copy.name,'Suppe (Kopie)');assert.equal(copy.id,'copy');});
test('restore retains previous state for recovery',()=>{const db=storage(),previous=db.getItem('main'),replacement=state();replacement.recipes[0].name='Neu';const restored=D.restore(db,'main','recovery',replacement);assert.equal(db.getItem('recovery'),previous);assert.deepEqual(JSON.parse(db.getItem('main')),restored);D.restore(db,'main','recovery',JSON.parse(db.getItem('recovery')));assert.equal(db.getItem('main'),previous);});
test('invalid input and storage failures do not overwrite current data',()=>{const db=storage(),before=db.getItem('main');assert.throws(()=>D.restore(db,'main','recovery',{}));assert.equal(db.getItem('main'),before);const replacement=state();replacement.recipes[0].name='Neu';const write=db.setItem;db.setItem=(key,value)=>{if(key==='main')throw Error('Quota exceeded');write(key,value);};assert.throws(()=>D.restore(db,'main','recovery',replacement));assert.equal(db.getItem('main'),before);assert.equal(db.getItem('recovery'),before);});
test('old backups remain valid and closed-day flags are validated',()=>{const s=state();delete s.weeks[s.weekStart].noCooking;assert.deepEqual(D.parseBackup(D.backup(s)),s);s.weeks[s.weekStart].noCooking=[false,true,false,false,false];assert.deepEqual(D.parseBackup(D.backup(s)),s);s.weeks[s.weekStart].noCooking[0]='false';assert.throws(()=>D.validateState(s));});
