const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const P=require('../dist/planning.js');
const recipes=[{id:'a',basePortions:10,ingredients:[{name:' Mehl ',amount:500,unit:'g',category:'Trockenwaren'},{name:'Milch',amount:500,unit:'ml',category:'Kühlung'}]},{id:'b',basePortions:10,ingredients:[{name:'mehl',amount:1,unit:'kg',category:'Trockenwaren'},{name:'Milch',amount:1,unit:'l',category:'Kühlung'}]}];
function week(){const w=P.emptyWeek(10);w.plan=['a','b',null,null,null];return w;}
test('units and daily portions aggregate independently',()=>{const w=week();w.dayPortions[1]=20;const items=P.items(w,recipes);assert.equal(items.length,2);assert.deepEqual(items.map(x=>[x.amount,x.unit]),[[2.5,'kg'],[2.5,'l']]);});
test('weight, volume and packages remain separate',()=>{const r=[{id:'a',basePortions:10,ingredients:['g','ml','Packung','Stk.'].map(unit=>({name:'X',amount:5,unit}))}];assert.equal(P.items(week(),r).length,4);});
test('legacy single week preserves recipe data, notes, portions and check',()=>{const saved={weekStart:'2026-09-14',portions:10,recipes,plan:['a',null,null,null,null],stockNotes:'Salz',checked:['Milch|ml']};const migrated=P.migrate(saved),w=migrated.weeks[saved.weekStart];assert.equal(w.stockNotes,'Salz');assert.deepEqual(w.dayPortions,[10,10,10,10,10]);assert.equal(w.checked.length,1);assert.deepEqual(migrated.recipes,recipes);assert.deepEqual(P.migrate(migrated),migrated);assert.equal(saved.version,undefined);});
test('partially checked legacy merged group is not marked bought',()=>{const s={weekStart:'2026-09-14',portions:10,recipes,weeks:{'2026-09-14':{plan:week().plan,checked:['Milch|ml']}}};assert.equal(P.migrate(s).weeks[s.weekStart].checked.length,0);s.weeks[s.weekStart].checked.push('Milch|l');assert.equal(P.migrate(s).weeks[s.weekStart].checked.length,1);});
test('quantity change clears only affected checks and does not resurrect them',()=>{const w=week();w.checked=P.items(w,recipes).map(x=>x.token);w.dayPortions[0]=11;P.reconcile(w,recipes);assert.equal(w.checked.length,0);w.dayPortions[0]=10;P.reconcile(w,recipes);assert.equal(w.checked.length,0);w.checked=P.items(w,recipes).map(x=>x.token);w.dayPortions[4]=20;P.reconcile(w,recipes);assert.equal(w.checked.length,2);});
test('copy is independent and resets shopping state',()=>{const w=week();w.stockNotes='source';w.checked=['x'];const c=P.copyWeek(w);c.plan[0]=null;c.dayPortions[0]=25;assert.equal(w.plan[0],'a');assert.equal(w.dayPortions[0],10);assert.deepEqual(c.checked,[]);assert.equal(c.stockNotes,'');});
function app(saved){const elements=new Map(),listeners={};const element=selector=>{if(!elements.has(selector))elements.set(selector,{value:'',dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(type,fn){this[type]=fn;},close(){}});return elements.get(selector);};let storage=saved?JSON.stringify(saved):null;const ctx=vm.createContext({console,Intl,Date,Map,Set,Promise,AbortController,setTimeout:()=>1,clearTimeout(){},confirm:()=>true,document:{querySelector:element,querySelectorAll:()=>[],addEventListener:(type,fn)=>listeners[type]=fn},window:{addEventListener(){},scrollTo(){}},navigator:{},localStorage:{getItem:()=>storage,setItem:(key,value)=>storage=value}});vm.runInContext(fs.readFileSync('dist/planning.js','utf8')+'\n'+fs.readFileSync('dist/data.js','utf8')+'\n'+fs.readFileSync('dist/app.js','utf8'),ctx);return{ctx,element,read:()=>JSON.parse(storage),run:code=>vm.runInContext(code,ctx)};}
test('app starts, persists migration, restores week after navigation and reload',()=>{const a=app();a.run('currentWeek().dayPortions[0]=12;currentWeek().stockNotes="original";save()');a.element('#next-week').click();assert.deepEqual(a.run('JSON.stringify(currentWeek().plan)'),JSON.stringify([null,null,null,null,null]));a.run('currentWeek().dayPortions[0]=80;save()');a.element('#previous-week').click();assert.equal(a.run('currentWeek().dayPortions[0]'),12);assert.equal(a.run('currentWeek().stockNotes'),'original');const b=app(a.read());assert.equal(b.run('currentWeek().dayPortions[0]'),12);assert.equal(b.run('state.weeks["2026-09-21"].dayPortions[0]'),80);});
test('UI day and whole-week controls, copy and checked tokens round trip',()=>{const a=app();a.element('#day-list').change({target:{dataset:{dayPortions:'1'},value:'20',checkValidity:()=>true}});assert.equal(a.run('currentWeek().dayPortions[1]'),20);const token=a.run('shoppingItems()[0].token');a.element('#shopping-list').change({target:{dataset:{item:token},checked:true}});assert.equal(a.run('currentWeek().checked.length'),1);assert.equal(app(a.read()).run('currentWeek().checked.length'),1);a.element('#portions').change({target:{value:'40',checkValidity:()=>true}});assert.equal(a.run('currentWeek().checked.length'),0);assert.equal(a.run('currentWeek().dayPortions.every(n=>n===40)'),true);a.element('#next-week').click();a.element('#copy-week').click();assert.equal(a.run('currentWeek().dayPortions[0]'),40);assert.equal(a.run('currentWeek().plan[0]'),'kartoffel');a.run('currentWeek().dayPortions[0]=50;save()');a.element('#previous-week').click();assert.equal(a.run('currentWeek().dayPortions[0]'),40);});
test('static entrypoint and service worker references exist',()=>{const html=fs.readFileSync('dist/index.html','utf8');for(const [,url] of html.matchAll(/(?:src|href)="\.\/([^"#]+)"/g))assert.ok(fs.existsSync('dist/'+url),url);const sw=fs.readFileSync('dist/sw.js','utf8');for(const [,url] of sw.matchAll(/"\.\/([^"#]+)"/g))assert.ok(fs.existsSync('dist/'+url),url);});
test('recipe form edits category and amount, rejects invalid input, and deletes planned recipe',()=>{
 const a=app();a.ctx.crypto={randomUUID:()=> 'new-recipe'};
 const fields={name:{value:'Neue Suppe'},side:{value:'Brot'},basePortions:{value:'10'},allergens:{value:'G'}};
 const values={name:'Milch',amount:'2',unit:'l',category:'Kühlung'};
 a.element('#ingredient-rows').querySelectorAll=()=>[{querySelector:selector=>({value:values[selector.match(/=(\w+)/)[1]]})}];
 const event={preventDefault(){},currentTarget:{reportValidity:()=>true,elements:fields}};
 a.element('#recipe-form').submit(event);assert.equal(a.run('recipe("new-recipe").ingredients[0].category'),'Kühlung');
 a.run('editingRecipeId="new-recipe";currentWeek().plan[0]="new-recipe";save()');values.amount='3';a.element('#recipe-form').submit(event);assert.equal(a.run('recipe("new-recipe").ingredients[0].amount'),3);
 values.amount='-1';a.element('#recipe-form').submit(event);assert.equal(a.run('recipe("new-recipe").ingredients[0].amount'),3);assert.ok(a.element('#recipe-error').textContent);
 a.element('#delete-recipe').click();assert.equal(a.run('recipe("new-recipe")'),undefined);assert.equal(a.run('currentWeek().plan[0]'),null);
});
test('imported text renders escaped in recipes, meal chooser and shopping',()=>{const a=app();a.run('state.recipes[0].name="<img src=x onerror=alert(1)>";state.recipes[0].ingredients[0].name="<script>bad</script>";renderAll()');assert.ok(!a.element('#recipe-list').innerHTML.includes('<img'));assert.ok(a.element('#recipe-list').innerHTML.includes('&lt;img'));assert.ok(!a.element('#shopping-list').innerHTML.includes('<script>'));});
test('invalid stored data is preserved rather than overwritten by samples',()=>{const a=app({broken:true});assert.deepEqual(a.read(),{broken:true});assert.equal(a.run('storageBlocked'),true);assert.ok(a.element('#storage-error').textContent);});
test('no-cooking days are excluded from purchase quantities and survive copy and backup',()=>{const a=app();const initial=a.run('shoppingItems().find(x=>x.name==="Kartoffeln").amount');a.run('currentWeek().noCooking[0]=true;save();renderAll()');assert.ok(a.run('shoppingItems().find(x=>x.name==="Kartoffeln").amount')<initial);assert.ok(a.element('#day-list').innerHTML.includes('Kein Kochen'));assert.ok(a.run('planShareText()').includes('Montag (14.09.): Kein Kochen'));assert.equal(app(a.read()).run('currentWeek().noCooking[0]'),true);assert.equal(a.run('Planning.copyWeek(currentWeek()).noCooking[0]'),true);assert.equal(a.run('KitchenData.parseBackup(KitchenData.backup(state)).weeks[state.weekStart].noCooking[0]'),true);});
test('print documents distinguish unplanned days, closed days and missing allergens',()=>{const a=app();a.run('currentWeek().noCooking[0]=true;currentWeek().plan[1]=null;state.recipes.find(r=>r.id===currentWeek().plan[2]).allergens=""');const html=a.run('outputDocument("plan")');assert.ok(html.includes('Kein Kochen'));assert.ok(html.includes('Noch nicht geplant'));assert.ok(html.includes('Nicht angegeben'));assert.ok(html.includes('Milch (einschließlich Laktose)'));assert.ok(!html.includes('Kartoffel-Spinat-Auflauf'));assert.equal((html.match(/<th scope="row">/g)||[]).length,5);});
test('shopping print includes multiline notes, quantity and purchased state without HTML injection',()=>{const a=app();a.run('currentWeek().stockNotes="Öl fehlt\\n<test> & Salz";currentWeek().checked=[shoppingItems()[0].token]');const html=a.run('outputDocument("shopping")');assert.ok(html.includes('Öl fehlt\n&lt;test&gt; &amp; Salz'));assert.ok(html.includes('paper-checkbox">✓'));assert.ok(html.includes('Portionen gesamt'));a.run('currentWeek().noCooking.fill(true)');assert.ok(a.run('outputDocument("shopping")').includes('Keine Zutaten geplant.'));});
test('allergen labels preserve unknown entries and never infer absence',()=>{const a=app();assert.equal(a.run('allergenText("")'),'Nicht angegeben');assert.equal(a.run('allergenText("A1, C, G, Sellerie, X9")'),'A1 – Weizen (Gluten); C – Eier; G – Milch (einschließlich Laktose); Sellerie; X9');});

test('recipe view shows quantities and allergens without changing stored data',()=>{const a=app();a.run('state.recipes[0].name="<Rezept>";state.recipes[0].ingredients[0].name="<Zutat>"');const before=a.run('JSON.stringify(state)'),stored=JSON.stringify(a.read());let opened=false;a.element('#recipe-view-dialog').showModal=()=>{opened=true;};a.run('openRecipeView(state.recipes[0].id)');assert.ok(opened);assert.equal(a.element('#recipe-view-title').textContent,'<Rezept>');const html=a.element('#recipe-view-content').innerHTML;assert.ok(html.includes('&lt;Zutat&gt;'));assert.ok(html.includes('Zutaten für'));assert.ok(html.includes('Allergene'));assert.ok(!/<input|<textarea|<select/.test(html));assert.equal(a.run('JSON.stringify(state)'),before);assert.equal(JSON.stringify(a.read()),stored);});
